name: accounting_portal
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Http Api
  http:

  edge_detection: ^1.1.1

  # PDF generation - path
  path_provider: ^1.6.24
  uuid: ^2.2.2
  # pdf: ^1.13.0
  fluttertoast: ^8.1.1
  permission_handler: 
  syncfusion_flutter_pdf: 
  dio: ^4.0.6
  pdf: ^1.4.0+1
  date_format: ^1.0.8
  
  

  # PDF View
  printing: ^3.7.2

  # Database
  hive: ^1.4.4+1
  hive_flutter: 
  



  ## Dependency injection
  get_it: ^5.0.3
  injectable: ^1.0.7

  #Font icons
  fontisto_flutter: ^3.1.0
  intl: ^0.17.0
  flutter_pagination: ^0.0.8
  html: ^0.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # mockito: ^4.1.3
  path: any

  # Injectable and dependency injection
  build_runner:
  injectable_generator: ^1.0.7
  very_good_analysis: ^1.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/load.gif  #   - images/a_dot_ham.jpeg



  fonts:
    - family: Lemon   
      fonts:
        - asset: assets/fonts/lemon.otf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf   
